Blatt3 fumer100

In [14]:
#A1 [LGT mit Backtracking]
import numpy as np
def lgt(v,w):
    S = np.zeros(((len(v)+1),(len(w)+1)))
    B = np.empty(((len(v)+1),(len(w)+1)),dtype=object)
    for a in range(0,1):
        for b in range(1,len(w)+1):
            B[a,b]="links"
            
    for c in range(1,len(v)+1):
        for d in range(0,1):
            B[c,d]="oben"
            
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
            if(v[i-1]==w[j-1]):
                S[i,j]=max(S[i-1,j],S[i,j-1],S[i-1,j-1]+1)
                if(max(S[i-1,j],S[i,j-1],S[i-1,j-1]+1)==S[i-1,j]):
                    B[i,j]="oben"
                if(max(S[i-1,j],S[i,j-1],S[i-1,j-1]+1)==S[i,j-1]):
                    B[i,j]="links"
                if(max(S[i-1,j],S[i,j-1],S[i-1,j-1]+1)==S[i-1,j-1]+1):
                    B[i,j]="oben-links"
            else:
                S[i,j]=max(S[i-1,j],S[i,j-1])
                if(S[i-1,j]==S[i,j-1]):
                    B[i,j]="oben/links"
                elif(max(S[i-1,j],S[i,j-1])==S[i-1,j]):
                    B[i,j]="oben"
                elif(max(S[i-1,j],S[i,j-1])==S[i,j-1]):
                    B[i,j]="links"
    
    score=S[(len(v))][(len(w))]
    print(S)
    print(B)
    return (score,B)

def backtrack_v(B,v,i,j):
    v_lgt=list(v)
    if i==0 and j==0:         
        print(v_lgt)
        return(v_lgt)
    
    if B[i,j]=="oben/links":
        v_lgt[i-1]="-"
        backtrack_v(B,v_lgt,i,j-1)
    if B[i,j]=="links":
        v_lgt[i-1]="-"
        backtrack_v(B,v_lgt,i,j-1)
    if B[i,j]=="oben":
        backtrack_v(B,v_lgt,i-1,j)
    if B[i,j]=="oben-links":
        backtrack_v(B,v_lgt,i-1,j-1)
        
def backtrack_w(B,w,i,j):
    w_lgt=list(w)
    if i==0 and j==0:         
        print(w_lgt)
        return(w_lgt)
    
    if B[i,j]=="oben/links":
        w_lgt[j-1]="-"
        backtrack_w(B,w_lgt,i-1,j)
    if B[i,j]=="links":
        backtrack_w(B,w_lgt,i,j-1)
    if B[i,j]=="oben":
        w_lgt[j-1]="-"
        backtrack_w(B,w_lgt,i-1,j)
    if B[i,j]=="oben-links":
        backtrack_w(B,w_lgt,i-1,j-1)
        
v = "ATGCG"
w = "ATCCGC"
S, B = lgt(v,w)
backtrack_v(B,v,len(v),len(w))
backtrack_w(B,w,len(v),len(w))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1.]
 [0. 1. 2. 2. 2. 2. 2.]
 [0. 1. 2. 2. 2. 3. 3.]
 [0. 1. 2. 3. 3. 3. 4.]
 [0. 1. 2. 3. 3. 4. 4.]]
[[None 'links' 'links' 'links' 'links' 'links' 'links']
 ['oben' 'oben-links' 'links' 'links' 'links' 'links' 'links']
 ['oben' 'oben' 'oben-links' 'links' 'links' 'links' 'links']
 ['oben' 'oben' 'oben' 'oben/links' 'oben/links' 'oben-links' 'links']
 ['oben' 'oben' 'oben' 'oben-links' 'oben-links' 'oben/links'
  'oben-links']
 ['oben' 'oben' 'oben' 'oben' 'oben/links' 'oben-links' 'oben/links']]
['A', 'T', '-', 'C', '-']
['A', 'T', 'C', 'C', 'G', '-']


In [6]:
#A2 GlobalAlignment Backtracking
#Habe es so verstanden, dass die in A1 ermittelten Lgts hier als neue v,w verwendet werden sollen(siehe *)
import numpy as np
def globalAlignment(v,w):
    mismatch=0
    match=1
    indel=-1
    S = np.zeros(((len(v)+1),(len(w)+1)))
    B = np.empty(((len(v)+1),(len(w)+1)),dtype=object)
    for a in range(0,1):
        for b in range(1,len(w)+1):
            S[a,b]=b*-1
            B[a,b]="links"
    for c in range(1,len(v)+1):
        for d in range(0,1):
            S[c,d]=c*-1
            B[c,d]="oben"
   
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
                
            if(v[i-1]==w[j-1]):
                S[i,j]=max(S[i-1,j]+indel,S[i,j-1]+indel,S[i-1,j-1]+match)
                
                if(max(S[i-1,j]+indel,S[i,j-1]+indel,S[i-1,j-1]+match)==S[i-1,j]+indel):
                    B[i,j]="oben"
                    
                if(max(S[i-1,j]+indel,S[i,j-1]+indel,S[i-1,j-1]+match)==S[i,j-1]+indel):
                    B[i,j]="links"
                    
                if(max(S[i-1,j]+indel,S[i,j-1]+indel,S[i-1,j-1]+match)==S[i-1,j-1]+match):
                    B[i,j]="oben-links"
            else:
                S[i,j]=max(S[i-1,j]+indel,S[i,j-1]+indel,S[i-1,j-1]+mismatch)
                if(S[i-1,j]==S[i,j-1]):
                    B[i,j]="oben/links"
                elif(max(S[i-1,j]+mismatch,S[i,j-1]+mismatch)==S[i-1,j]):
                    B[i,j]="oben"
                elif(max(S[i-1,j]+mismatch,S[i,j-1]+mismatch)==S[i,j-1]):
                    B[i,j]="links"
    
    score=S[(len(v))][(len(w))]
    print(S)
    print(B)
    return (score,B,S)

def backtrack_v(B,v,i,j,):
    v_lgt=list(v)
    if i==0 and j==0:         
        print(v_lgt)
        return(v_lgt)
    
    if B[i,j]=="oben/links":
        v_lgt[i-1]="-"
        
        backtrack_v(B,v_lgt,i,j-1)
    if B[i,j]=="links":
        v_lgt[i-1]="-"
    
        backtrack_v(B,v_lgt,i,j-1)
    if B[i,j]=="oben":
      
        backtrack_v(B,v_lgt,i-1,j)
    if B[i,j]=="oben-links":
       
        backtrack_v(B,v_lgt,i-1,j-1)
        
        
def backtrack_w(B,w,i,j):
    w_lgt=list(w)
    if i==0 and j==0:         
        print(w_lgt)
        return(w_lgt)
    
    if B[i,j]=="oben/links":
        w_lgt[j-1]="-"
       
        backtrack_w(B,w_lgt,i-1,j)
    if B[i,j]=="links":
       
        backtrack_w(B,w_lgt,i,j-1)
    if B[i,j]=="oben":
        w_lgt[j-1]="-"
        
        backtrack_w(B,w_lgt,i-1,j)
    if B[i,j]=="oben-links":
        
        backtrack_w(B,w_lgt,i-1,j-1)
        
v = "AT-C-"     #*
w = "ATCCG-"    #*
#a = "ATGCG"     zur Sicherheit kann auch das hier verwendet werden, falls ich es doch falsch verstanden habe.
#b = "ATCCGC"
score, B, S = globalAlignment(v,w)
#score, B, S = globalAlignment(a,b)
print(score)
np.savetxt('alignment.txt', S,fmt='%d' ,delimiter=',')
global_v = backtrack_v(B,v,len(v),len(w))
global_w = backtrack_w(B,w,len(v),len(w))
#global_a = backtrack_v(B,a,len(a),len(a))
#global_b = backtrack_w(B,b,len(b),len(b))

[[ 0. -1. -2. -3. -4. -5. -6.]
 [-1.  1.  0. -1. -2. -3. -4.]
 [-2.  0.  2.  1.  0. -1. -2.]
 [-3. -1.  1.  2.  1.  0.  0.]
 [-4. -2.  0.  2.  3.  2.  1.]
 [-5. -3. -1.  1.  2.  3.  3.]]
[[None 'links' 'links' 'links' 'links' 'links' 'links']
 ['oben' 'oben-links' 'links' 'links' 'links' 'links' 'links']
 ['oben' 'oben' 'oben-links' 'links' 'links' 'links' 'links']
 ['oben' 'oben' 'oben' 'oben/links' 'links' 'links' 'oben-links']
 ['oben' 'oben' 'oben' 'oben-links' 'oben-links' 'links' 'links']
 ['oben' 'oben' 'oben' 'oben' 'oben' 'oben/links' 'oben-links']]
3.0
['A', 'T', '-', '-', '-']
['A', 'T', '-', 'C', 'G', '-']


In [7]:
#A3 Global alignment mit Scoring matrix
#Scores der Beiden Alignments + Antwort der Aufgabe als print unten
#Erstelltes df und dictonary delta geprintet
import pandas as pd
import numpy as np

def lese_scoring_matrix(file):
    matrix = pd.read_fwf(file, sep=' ',skiprows=6,index_col=0)
    deltaUnsorted = matrix.to_dict()
    delta={}
    for r, v in matrix.iterrows():
        for c, v1 in v.iteritems():
            delta.update({(r,c): v1})
    print(matrix)
    print(delta)
    return delta

def globalAlignmentMitScoringMatrix(v,w,indel,delta):
    mismatch=0
    match=1
    S = np.zeros(((len(v)+1),(len(w)+1)))
    for a in range(0,1):
        for b in range(1,len(w)+1):
            S[a,b]=b*-1
            
    for c in range(1,len(v)+1):
        for d in range(0,1):
            S[c,d]=c*-1
            
   
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
                
            if(v[i-1]==w[j-1]):
                S[i,j]=max(S[i-1,j]+indel,S[i,j-1]+indel,S[i-1,j-1]+delta.get((v[i-1],w[j-1])))
                
               
            else:
                S[i,j]=max(S[i-1,j]+indel,S[i,j-1]+indel,S[i-1,j-1]+delta.get((v[i-1],w[j-1])))
                
    
    score=S[(len(v))][(len(w))]
    return (S,score)

file ='Dateien/blosum62.txt'
v='MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR'
w='MGLSDGEWQLVLNVWGKVEADIPGHGQEVLIRLFKGHPETLEKFDKFKHLKSEDEMKASEDLKKHGATVLTALGGILKKKGHHEAEIKPLAQSHATKHKIPVKYLEFISECIIQVLQSKHPGDFGADAQGAMNKALELFRKDMASNYKELGFQG'
delta = lese_scoring_matrix(file)
S, score = globalAlignmentMitScoringMatrix(v,w,-5,delta)
np.savetxt('global_aln.txt', S,fmt='%d' ,delimiter=',')
S1, score1 = globalAlignmentMitScoringMatrix(v,w,0,delta)
print(score)
print(score1)
print('Da Indels mit einem score von 0 weniger bestraft werden ist auch der Score des Alignments viel höher(3-fach) als bei einem Indelscore von -5, dadurch sind auch die Zwischenscores groesser als bei dem alignment mit niedriegerer Bestrafung')

   A  R  N  D  C  Q  E  G  H  I  ...  P  S  T   W  Y  V  B  Z  X  *
A  4 -1 -2 -2  0 -1 -1  0 -2 -1  ... -1  1  0  -3 -2  0 -2 -1  0 -4
R -1  5  0 -2 -3  1  0 -2  0 -3  ... -2 -1 -1  -3 -2 -3 -1  0 -1 -4
N -2  0  6  1 -3  0  0  0  1 -3  ... -2  1  0  -4 -2 -3  3  0 -1 -4
D -2 -2  1  6 -3  0  2 -1 -1 -3  ... -1  0 -1  -4 -3 -3  4  1 -1 -4
C  0 -3 -3 -3  9 -3 -4 -3 -3 -1  ... -3 -1 -1  -2 -2 -1 -3 -3 -2 -4
Q -1  1  0  0 -3  5  2 -2  0 -3  ... -1  0 -1  -2 -1 -2  0  3 -1 -4
E -1  0  0  2 -4  2  5 -2  0 -3  ... -1  0 -1  -3 -2 -2  1  4 -1 -4
G  0 -2  0 -1 -3 -2 -2  6 -2 -4  ... -2  0 -2  -2 -3 -3 -1 -2 -1 -4
H -2  0  1 -1 -3  0  0 -2  8 -3  ... -2 -1 -2  -2  2 -3  0  0 -1 -4
I -1 -3 -3 -3 -1 -3 -3 -4 -3  4  ... -3 -2 -1  -3 -1  3 -3 -3 -1 -4
L -1 -2 -3 -4 -1 -2 -3 -4 -3  2  ... -3 -2 -1  -2 -1  1 -4 -3 -1 -4
K -1  2  0 -1 -3  1  1 -2 -1 -3  ... -1  0 -1  -3 -2 -2  0  1 -1 -4
M -1 -1 -2 -3 -1  0 -2 -3 -2  1  ... -2 -1 -1  -1 -1  1 -3 -1 -1 -4
F -2 -3 -3 -3 -2 -3 -3 -3 -1  0  ... -4 -2 -2   

In [13]:
#A4 Local alignment
import pandas as pd
import numpy as np

def lese_scoring_matrix(file):
    matrix = pd.read_fwf(file, sep=' ',skiprows=6,index_col=0)
    deltaUnsorted = matrix.to_dict()
    delta={}
    for r, v in matrix.iterrows():
        for c, v1 in v.iteritems():
            delta.update({(r,c): v1})

    return delta

def localAlignment(v,w,delta):
    indel=-5
    S = np.zeros(((len(v)+1),(len(w)+1)))
    B = np.empty(((len(v)+1),(len(w)+1)),dtype=object)
    for a in range(0,1):
        for b in range(1,len(w)+1):
            B[a,b]="links"
    for c in range(1,len(v)+1):
        for d in range(0,1):
 
            B[c,d]="oben"
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
                
            if(v[i-1]==w[j-1]):
                S[i,j]=max(S[i-1,j]+indel,S[i,j-1]+indel,S[i-1,j-1]+delta.get((v[i-1],w[j-1])))
                if(max(S[i-1,j]+indel,S[i,j-1]+indel,S[i-1,j-1]+delta.get((v[i-1],w[j-1])))==S[i-1,j]+indel):
                    B[i,j]="oben"
                    
                 
                if(max(S[i-1,j]+indel,S[i,j-1]+indel,S[i-1,j-1]+delta.get((v[i-1],w[j-1])))==S[i,j-1]+indel):
                    B[i,j]="links"
                    
                if(max(S[i-1,j]+indel,S[i,j-1]+indel,S[i-1,j-1]+delta.get((v[i-1],w[j-1])))==S[i-1,j-1]+delta.get((v[i-1],w[j-1]))):
                    B[i,j]="oben-links"
                if S[i,j]<0:
                    S[i,j]=0  
            else:
                S[i,j]=max(S[i-1,j]+indel,S[i,j-1]+indel,S[i-1,j-1]+delta.get((v[i-1],w[j-1])))
                if(S[i-1,j]+indel==S[i,j-1]+indel):
                    B[i,j]="oben/links"
                elif(max(S[i-1,j]+indel,S[i,j-1]+indel)==S[i-1,j]+indel):
                    B[i,j]="oben"
                elif(max(S[i-1,j]+indel,S[i,j-1]+indel)==S[i,j-1]+indel):
                    B[i,j]="links"
                if(max(S[i-1,j]+indel,S[i,j-1]+indel,S[i-1,j-1]+delta.get((v[i-1],w[j-1])))==S[i-1,j-1]+delta.get((v[i-1],w[j-1]))):
                    B[i,j]="oben-links"
                if S[i,j]<0:
                    S[i,j]=0
    
    score=S[(len(v))][(len(w))]
    np.savetxt('local_aln.txt', S,fmt='%d' ,delimiter=',')
    return (B,S,score)

def backtrack_v(B,v,i,j,S):
    v_lgt=list(v)
    if (i==0 and j==0)or(S[i,j]==0):  #Diese Abbruchbedingung weil Lokales Alignment       
        print(v_lgt)
        print(len(v_lgt))
        return(v_lgt)
       
    if B[i,j]=="oben/links":
        v_lgt[i-1]="-"
       
        backtrack_v(B,v_lgt,i,j-1,S)
    if B[i,j]=="links":
        v_lgt[i-1]="-"
        backtrack_v(B,v_lgt,i,j-1,S)
    if B[i,j]=="oben":
        
        backtrack_v(B,v_lgt,i-1,j,S)
    if B[i,j]=="oben-links":
 
        backtrack_v(B,v_lgt,i-1,j-1,S)
        
        
def backtrack_w(B,w,i,j,S):
    w_lgt=list(w)
    if (i==0 and j==0)or(S[i,j]==0):         
        print(w_lgt)
        print(len(w_lgt))
        return(w_lgt)
        
    if B[i,j]=="oben/links":
        w_lgt[j-1]="-"
        backtrack_w(B,w_lgt,i-1,j,S)
        
    if B[i,j]=="links":
        
        backtrack_w(B,w_lgt,i,j-1,S)
        
    if B[i,j]=="oben":
        w_lgt[j-1]="-"
        backtrack_w(B,w_lgt,i-1,j,S)
        
    if B[i,j]=="oben-links":
        backtrack_w(B,w_lgt,i-1,j-1,S)
file ='Dateien/blosum62.txt'
v='MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR'
w='MGLSDGEWQLVLNVWGKVEADIPGHGQEVLIRLFKGHPETLEKFDKFKHLKSEDEMKASEDLKKHGATVLTALGGILKKKGHHEAEIKPLAQSHATKHKIPVKYLEFISECIIQVLQSKHPGDFGADAQGAMNKALELFRKDMASNYKELGFQG'
print(len(v),len(w))
delta = lese_scoring_matrix(file)
B, S, score = localAlignment(v,w,delta)
i, j = np.unravel_index(S.argmax(),S.shape)#Koordinaten des Maximums von S
print(B)
print(np.max(S))
global_v = backtrack_v(B,v,i,j,S)
global_w = backtrack_w(B,w,i,j,S)
print('der Score ist 135')

142 154
[[None 'links' 'links' ... 'links' 'links' 'links']
 ['oben' 'oben-links' 'links' ... 'oben-links' 'oben-links' 'oben-links']
 ['oben' 'oben-links' 'oben-links' ... 'oben-links' 'oben-links'
  'oben-links']
 ...
 ['oben' 'oben-links' 'oben-links' ... 'oben-links' 'oben-links' 'links']
 ['oben' 'oben-links' 'oben-links' ... 'oben-links' 'links' 'oben-links']
 ['oben' 'oben-links' 'oben-links' ... 'links' 'oben-links' 'links']]
135.0
['M', 'V', 'L', 'S', 'P', 'A', 'D', 'K', 'T', 'N', 'V', 'K', 'A', 'A', 'W', 'G', 'K', 'V', 'G', 'A', 'H', 'A', 'G', 'E', 'Y', 'G', 'A', 'E', 'A', 'L', 'E', 'R', 'M', 'F', 'L', 'S', 'F', '-', 'T', 'T', 'K', 'T', '-', 'F', 'P', 'H', '-', 'D', 'L', 'S', 'H', 'G', 'S', 'A', 'Q', 'V', 'K', 'G', 'H', 'G', 'K', 'K', 'V', 'A', 'D', 'A', 'L', 'T', 'N', 'A', 'V', 'A', 'H', 'V', 'D', 'D', 'M', 'P', 'N', '-', 'L', 'S', 'A', 'L', 'S', 'D', 'L', 'H', 'A', 'H', 'K', 'L', 'R', 'V', 'D', 'P', 'V', 'N', '-', 'K', 'L', 'L', 'S', 'H', 'C', 'L', 'L', 'V', 'T', '-', 'A', 