 Blatt 2                                                               fumer100

In [1]:
import sys
import numpy as np
def LGT(v,w):
    S = np.zeros(((len(v)+1),(len(w)+1)))
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
            if(v[i-1]==w[j-1]):
                S[i,j]=max(S[i-1,j],S[i,j-1],S[i-1,j-1]+1)
            else:
                S[i,j]=max(S[i-1,j],S[i,j-1])
    return S

v = "ATGCG"
w = "ATCCGC"
S=LGT(v,w)
np.savetxt('S.txt', S,fmt='%d' ,delimiter=',')

In [6]:
import numpy as np
def lgt(v,w):
    S = np.zeros(((len(v)+1),(len(w)+1)))
    B = np.empty(((len(v)+1),(len(w)+1)),dtype=object)
    for a in range(0,1):
        for b in range(0,len(w)+1):
            S[a,b]=b*-1
    for c in range(0,len(v)+1):
        for d in range(0,1):
            S[c,d]=c*-1
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
            if(v[i-1]==w[j-1]):
                S[i,j]=max(S[i-1,j],S[i,j-1],S[i-1,j-1]+1)
                if(max(S[i-1,j],S[i,j-1],S[i-1,j-1]+1)==S[i-1,j]):
                    B[i,j]="oben"
                if(max(S[i-1,j],S[i,j-1],S[i-1,j-1]+1)==S[i,j-1]):
                    B[i,j]="links"
                if(max(S[i-1,j],S[i,j-1],S[i-1,j-1]+1)==S[i-1,j-1]+1):
                    B[i,j]="oben-links"
            else:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                S[i,j]=max(S[i-1,j],S[i,j-1])
                if(S[i-1,j]==S[i,j-1]):
                    B[i,j]="oben/links"
                elif(max(S[i-1,j],S[i,j-1])==S[i-1,j]):
                    B[i,j]="oben"
                elif(max(S[i-1,j],S[i,j-1])==S[i,j-1]):
                    B[i,j]="links"
    
    score=S[(len(v))][(len(w))]
    print(S)
    print(B)
    return (score,B)

v = "ATGCG"
w = "ATCCGC"
S=lgt(v,w)



[[ 0. -1. -2. -3. -4. -5. -6.]
 [-1.  1.  1.  1.  1.  1.  1.]
 [-2.  1.  2.  2.  2.  2.  2.]
 [-3.  1.  2.  2.  2.  3.  3.]
 [-4.  1.  2.  3.  3.  3.  4.]
 [-5.  1.  2.  3.  3.  4.  4.]]
[[None None None None None None None]
 [None 'oben-links' 'links' 'links' 'links' 'links' 'links']
 [None 'oben' 'oben-links' 'links' 'links' 'links' 'links']
 [None 'oben' 'oben' 'oben/links' 'oben/links' 'oben-links' 'links']
 [None 'oben' 'oben' 'oben-links' 'oben-links' 'oben/links' 'oben-links']
 [None 'oben' 'oben' 'oben' 'oben/links' 'oben-links' 'oben/links']]
